services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: always
    ports:
      - "8080:8080"
    command: ["/api-gateway"]

  employee-service:
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    container_name: employee_service
    restart: always
    depends_on:
      - postgres
    ports:
      - "50051:50051"
    command: ["/employee-service"]